#!/bin/bash

if [ -z $1 ]; then
  echo "Usage: compile <problem_number>"
  exit 1
fi

if [ ! -f solutions/$1.cc ]; then
  echo "solutions/$1.cc does not exist."
  exit 1
fi

g++ solutions/$1.cc -o a.out
clear
echo "running solutions/$1.cc"
echo "========================"
./a.out
rm a.out
